[theme]
primaryColor = "#4CAF50"                # Main accent color (e.g., for buttons and links)
backgroundColor = "#F5F5F5"             # Main background color
secondaryBackgroundColor = "#FFFFFF"   # Sidebar and widget background
textColor = "#000000"                   # Text color
font = "sans serif"                     # Font style: "sans serif", "serif", or "monospace"
